server:
  port: 9090
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: none
  #    properties:
  #      hibernate:
  #        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/server
    username: dbuser
    password: password

logging:
  level:
    ru:
      practicum: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
          JpaTransactionManager: DEBUG

      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
